# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      # Security patches
      security-patches:
        applies-to: security-updates
        dependency-type: production
        update-types:
          - "patch"
      security-patches-dev:
        applies-to: security-updates
        dependency-type: development
        update-types:
          - "patch"

      # Security
      security:
        applies-to: security-updates
        dependency-type: production
        update-types:
          - "minor"
          - "major"
      security-dev:
        applies-to: security-updates
        dependency-type: development
        update-types:
          - "minor"
          - "major"

      # Version patches
      patches:
        applies-to: version-updates
        dependency-type: production
        update-types: "patch"
      patches-dev:
        applies-to: version-updates
        dependency-type: development
        update-types: "patch"

      # Third parties
      sanity:
        patterns:
          - "sanity"
          - "sanity*"
          - "@sanity/*"
        update-types:
          - "patch"
          - "minor"
      next:
        patterns:
          - "next"
          - "next*"
          - "@next/*"
        update-types:
          - "patch"
          - "minor"
      mui:
        patterns:
          - "@mui/*"
          - "@emotion/*"
          - "styled-components"
          - "postcss"
          - "tailwindcss"
          - "tailwindcss*"
          - "@tailwindcss/*"
        update-types:
          - "patch"
          - "minor"
