# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      core:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "react"
          - "react-*"
          - "@types/react"
          - "@types/react-*"
          - "@types/node"
          - "typescript"
          - "server-only"
      next-sanity:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "next-sanity"
          - "next-sanity-*"
      next:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "next"
          - "next-*"
          - "*-next"
          - "@next/*"
          - "nextjs-*"
      sanity:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "@sanity/*"
          - "sanity"
          - "sanity-*"
          - "*-sanity"
      mui:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "@mui/*"
      dev:
        update-types:
          - "minor"
          - "patch"
        dependency-type: "development"
      default:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
